"""empty message

Revision ID: 1cb83ad5d2af
Revises: b3c66247d968
Create Date: 2022-02-22 21:42:28.569084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb83ad5d2af'
down_revision = 'b3c66247d968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversationgroup_id', sa.Integer(), nullable=False))
    op.drop_constraint('message_conversation_group_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversationgroup', ['conversationgroup_id'], ['id'])
    op.drop_column('message', 'conversation_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversation_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_conversation_group_id_fkey', 'message', 'conversationgroup', ['conversation_group_id'], ['id'])
    op.drop_column('message', 'conversationgroup_id')
    # ### end Alembic commands ###
