"""empty message

Revision ID: 297de2845368
Revises: 6ed5520d2985
Create Date: 2022-02-24 00:13:55.519723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297de2845368'
down_revision = '6ed5520d2985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
