"""empty message

Revision ID: 6ed5520d2985
Revises: c8755ca4c404
Create Date: 2022-02-23 20:55:12.663115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed5520d2985'
down_revision = 'c8755ca4c404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
