"""empty message

Revision ID: bc0a6e5e1a05
Revises: 297de2845368
Create Date: 2022-02-24 10:35:59.531130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0a6e5e1a05'
down_revision = '297de2845368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
