"""empty message

Revision ID: c8755ca4c404
Revises: 5879a831adba
Create Date: 2022-02-23 15:55:42.482083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8755ca4c404'
down_revision = '5879a831adba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'message',
        sa.Column(
            'sender_id',
            sa.Integer(),
            nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
