"""empty message

Revision ID: d7489b526a1f
Revises: 7c794e39fe26
Create Date: 2022-02-23 10:42:59.623475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7489b526a1f'
down_revision = '7c794e39fe26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationgroup_user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('conversationgroup_user_message_id_fkey', 'conversationgroup_user', type_='foreignkey')
    op.create_foreign_key(None, 'conversationgroup_user', 'user', ['user_id'], ['id'])
    op.drop_column('conversationgroup_user', 'id')
    op.drop_column('conversationgroup_user', 'message_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationgroup_user', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversationgroup_user', type_='foreignkey')
    op.create_foreign_key('conversationgroup_user_message_id_fkey', 'conversationgroup_user', 'message', ['message_id'], ['id'])
    op.create_index('ix_conversationgroup_user_id', 'conversationgroup_user', ['id'], unique=False)
    op.drop_column('conversationgroup_user', 'user_id')
    # ### end Alembic commands ###
